name: DFAF

question_features_dim: 1280
vision_features_dim: 1024
hidden_features_dim: 512
num_inter_head: 8
num_intra_head: 8
num_block: 1

loss_type: BCE  ## can be [BCE, SCE, KL, MultiLabel]
apply_mask: false
freeze_fasterRCNN: true
enable_image: false
enable_hint: false

max_choices: 2048
max_question_words: 16
max_hint_words: 64
num_vision_tokens: 32

vocab_path: ./datasets/assets/scienceqa_vocab.json
vocab_path_slurm: null
vocab_path_charlie: null