name: TFUSE_SCRATCH

token_features_dim: 1024
transformer_nheads: 8
num_encoder_layers: 3
num_decoder_layers: 3
global_pool: mean  ## can be [cls, mean, max]
classifier_mid_features: 1024
classifier_dropout: 0.5

loss_type: BCE  ## can be [BCE, SCE, KL, MultiLabel]
apply_mask: false
enable_image: false
enable_hint: false

max_choices: 2048
max_question_words: 16
max_hint_words: 32
num_vision_tokens: 32

vocab_path: ./datasets/assets/scienceqa_vocab.json