name: scienceqa

lr: 1e-4
eval_interval: 1

dataset: 
  name: ScienceQA

  data_dir: /mnt/seagate12t/VQA/scienceqa
  data_dir_slurm: None
  data_dir_charlie: /home/puhao/thu/ml/data/scienceqa

  image_resolution: 224
  max_choices: ${model.max_choices}
  answerable_only: true
  vocab_path: ${model.vocab_path}
  vocab_path_slurm: ${model.vocab_path_slurm}
  vocab_path_charlie: ${model.vocab_path_charlie}
  device: cuda

train:
  num_epochs: 100
  batch_size: 32
  num_workers: 4
  log_step: 10

test:
  batch_size: 32
  num_workers: 0

visualizer:
  visualize: false
