## config/default.yaml
hydra:
  run:
    dir: ${exp_dir}
  output_subdir: null

defaults:
  - _self_
  - model: null
  - task: null

slurm: false
output_dir: outputs
exp_name: default
exp_dir: ${output_dir}/${now:%Y-%m-%d_%H-%M-%S}_${exp_name}
tb_dir: ${exp_dir}/tb_logs
vis_dir: ${exp_dir}/visual
ckpt_dir: ${exp_dir}/ckpts

# for visualization in test
gpu: 0
