META:
  - './ScienceQA_Data/problems.json'
sqa:
  name: SQATask
  dataloader:
    batch_size: 8
    num_workers: 8
  dataset:
    name: SQADataset
    split: test
    root: ./ScienceQA_Data
  gen_kwargs:
    max_length: 128
    top_k: 5
    num_beams: 1
    do_sample: False
    use_cache: True
